name: Release
on:
    push:
        branches:
            - master
            - next
            - beta
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - name: Install pnpm
              run: npm i -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Run tests.
              run: pnpm test
              env:
                  CI: true
    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [ test ]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - name: Install pnpm
              run: npm i -g pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build distributions
              run: pnpm run build
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release